--Task table
CREATE TABLE task (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      short_desc varchar(255) not null,
                      details text,
                      start_date timestamp not null,
                      end_date timestamp,
                      group_id bigint
);

create sequence task_sequence start with 1 increment by 1;